import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import "./layout.css";
import Sidebar from "../../components/layouts/Sidebar";
import Header from "../../components/layouts/Header";
import Footer from "../../components/layouts/Footer";
import Up from "@/components/UI/Up";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Top app",
  description: "Generated by create next app",
};

export default function SiteLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <div className="wrapper">
        <div className="md:hidden">
          <Header className="header" />
        </div>
        <Sidebar className="sidebar" />
        <main className="main">{children}</main>
        <Footer className="footer" />
        <Up />
      </div>
    </div>
  );
}
