import { Metadata } from "next";
import Title from "../../components/UI/Title";
import HomeClient from "./components/HomeClient";
import { getMenu } from "@/api/menu";
import Menu from "./components/Menu";

export async function generateMetadata(): Promise<Metadata> {
  return {
    title: "Top app",
    description: "Generated by create next app",
  };
}

export default function Home() {
  return (
    <div>
      <Title tag="h1">Welcome to the Top App</Title>
      <HomeClient />
    </div>
  );
}
