import type { Metadata } from "next";
import "../globals.css";
import Title from "@/components/UI/Title";

export const metadata: Metadata = {
  title: "Top app",
  description: "Generated by create next app",
};

export default function AboutTemplate({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <Title tag="h1">About Us</Title>
      <div className="flex-1 p-4">{children}</div>
    </div>
  );
}
